### ISSUE TITLE
Import from android sources

### ISSUE THREAD

**Issue by vxcamiloxv** [mopemope/meghanada-emacs#128]
Hi, first, thanks for meghanada.

I have a question, meghanada should be work with `gradle/android` projects? some extra configuration step?, currently for all imports from android sources show `package android.os does not exist`

- Emacs version: `GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05`

- Project information: 
```
System:
--------------------------------------------------------------------------------
os: Gnu/Linux
osVersion: 4.14.70-gnu-1-lts
osArch: amd64

Meghanada:
--------------------------------------------------------------------------------
meghanadaVersion: 1.0.8-3297bd8
meghanadaPath: ~/.emacs.d/external/meghanada-server/meghanada-1.0.8.jar
meghanadaServerPort: 33621
home: ~/.emacs.d/external/meghanada-server
useFastBoot: true
classCompletionMatcher: prefix
completionMatcher: prefix
useJavaVersion: 1.8
javacArg: -Xlint:all
useSourceCache: true
cacheInProject: true
cacheRoot: ~/.cache/meghanada
useExternalBuilder: false
clearCacheOnStart: false
isSkipBuildSubProjects: true
useAOSPStyleFormat: false
mavenLocalRepository: ~/.m2/repository
useFullTextSearch: false

Java:
--------------------------------------------------------------------------------
javaHome: /usr/lib/jvm/java-8-openjdk/jre
javaVersion: 1.8.0_181
compileSource: 1.8
compileTarget: 1.8
javac8Args: []
allClasspath:
  ~/simple-email/app/build/classes/java/main
  ~/simple-email/app/build/classes/java/test

SystemProperties:
  sun.cpu.isalist: 
  meghanada.javac.arg: -Xlint:all
  new-project-database: ~/simple-email/app/.meghanada/app_ee5a22b4f061b93f_fb18ca7328160281
  meghanada.skip.build.subprojects: true
  sun.io.unicode.encoding: UnicodeLittle
  sun.cpu.endian: little
  java.vendor.url.bug: http://bugreport.sun.com/bugreport/
  meghanada.format: sexp
  file.separator: /
  java.vendor: Oracle Corporation
  sun.boot.class.path: /usr/lib/jvm/java-8-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk/jre/classes
  java.ext.dirs: /usr/lib/jvm/java-8-openjdk/jre/lib/ext:/usr/java/packages/lib/ext
  java.version: 1.8.0_181
  java.vm.info: mixed mode
  awt.toolkit: sun.awt.X11.XToolkit
  user.language: en
  java.specification.vendor: Oracle Corporation
  sun.java.command: ~/.emacs.d/external/meghanada-server/meghanada-1.0.8.jar -p 0
  java.home: /usr/lib/jvm/java-8-openjdk/jre
  sun.arch.data.model: 64
  java.vm.specification.version: 1.8
  java.class.path: ~/.emacs.d/external/meghanada-server/meghanada-1.0.8.jar
  meghanada.completion.matcher: prefix
  file.encoding: UTF-8
  java.specification.version: 1.8
  java.awt.printerjob: sun.print.PSPrinterJob
  library.jansi.path: ~/.gradle/native/jansi/1.14/linux64
  sun.io.useCanonCaches: false
  os.version: 4.14.70-gnu-1-lts
  meghanada.cache.in.project: true
  sun.management.compiler: HotSpot 64-Bit Tiered Compilers
  java.net.preferIPv4Stack: true
  java.specification.name: Java Platform API Specification
  java.class.version: 52.0
  java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
  meghanada.search.static.method.classes: java.util.Objects,org.junit.Assert
  sun.jnu.encoding: UTF-8
  meghanada-server.version: 1.0.8-3297bd8
  meghanada.maven.path: mvn
  os.name: Linux
  java.vm.specification.vendor: Oracle Corporation
  java.io.tmpdir: /tmp/1540912778125-0
  line.separator: 

  project.root: ~/simple-email/app
  java.endorsed.dirs: /usr/lib/jvm/java-8-openjdk/jre/lib/endorsed
  os.arch: amd64
  meghanada.class.completion.matcher: prefix
  java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
  java.runtime.version: 1.8.0_181-b13
  home: ~/.emacs.d/external/meghanada-server
  java.vm.specification.name: Java Virtual Machine Specification
  user.dir: ~/brightspot
  meghanada.server.port: 33621
  user.country: US
  sun.java.launcher: SUN_STANDARD
  sun.os.patch.level: unknown
  java.vm.name: OpenJDK 64-Bit Server VM
  file.encoding.pkg: sun.io
  path.separator: :
  java.vm.vendor: Oracle Corporation
  java.vendor.url: http://java.oracle.com/
  sun.boot.library.path: /usr/lib/jvm/java-8-openjdk/jre/lib/amd64
  java.vm.version: 25.181-b13
  java.runtime.name: OpenJDK Runtime Environment

Project:
--------------------------------------------------------------------------------
project: gradle
projectRoot: ~/simple-email/app
gradlePrepareCompileTask: []
gradlePrepareTestCompileTask: []
projectDatbase: ~/simple-email/app/.meghanada/app_ee5a22b4f061b93f_fb18ca7328160281
projectDatabaseSize:   3.00MB
source-formatter: google 
sources:
  ~/simple-email/src/main/java
resources:
output:
  ~/simple-email/app/build/classes/java/main
testSources:
  ~/simple-email/src/test/java
testResources:
testOutput:
  ~/simple-email/app/build/classes/java/test
dependencies:

```
The only odd thing I saw is the `user.dir:` point to another directory outside to the project and don't have any relation
